# vim:ft=ruby:tabstop=2:softtabstop=2:shiftwidth=2

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"
  config.vm.box_check_update = false
  config.ssh.forward_agent = true  
  config.ssh.insert_key = false
  config.vm.provision :shell, :inline => <<-'EOF'
      set -x
      ln -sfv /usr/share/zoneinfo/America/Chicago /etc/localtime
      cd /vagrant/files/
      cp -v inputrc vimrc /etc/
      cp -v zzz_vagrant.sh prompt.sh bashrc.local.sh /etc/profile.d/
      cd -
      ssh-add -L >> /home/vagrant/.ssh/authorized_keys
      mkdir /root/.ssh
      ssh-add -L >> /root/.ssh/authorized_keys
      chmod 700 /root/.ssh
      chmod 600 /root/.ssh/authorized_keys
      sed -i '/alias /d' /root/.bashrc
      sed -i -e 's/xfs     defaults/xfs nobarrier/g' /etc/fstab
      sed -i -e 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
      sed -i -e 's/rhgb quiet//g' /etc/default/grub
      grub2-mkconfig -o /etc/grub2.cfg
    EOF
  config.vm.provision :shell, :inline => <<-EOF
      set -x
      yum erase -y linux-firmware $(</vagrant/files/unnecessary_packages)
      yum install -y https://download.ceph.com/rpm-luminous/el7/noarch/ceph-release-1-0.el7.noarch.rpm
      yum install -y epel-release
      yum install -y dstat mlocate vim-enhanced bash-completion-extras python-setuptools ceph-deploy
    EOF
  config.vm.provision :shell, :privileged => false, :inline => <<-EOF
      ssh-keyscan 127.0.0.1 >> ~/.ssh/known_hosts 2> /dev/null
      ceph-deploy install --release=luminous 127.0.0.1
    EOF
  config.vm.provision :shell, :inline => <<-EOF
      set -x
      updatedb
      yum clean all
      time dd if=/dev/zero of=/EMPTY bs=1M; rm -fv /EMPTY
    EOF
end
